/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
  };
  blocks: {};
  collections: {
    admins: Admin;
    media: Media;
    pages: Page;
    posts: Post;
    'menu-items': MenuItem;
    'team-members': TeamMember;
    'form-submissions': FormSubmission;
    exports: Export;
    redirects: Redirect;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
    'payload-query-presets': PayloadQueryPreset;
  };
  collectionsJoins: {};
  collectionsSelect: {
    admins: AdminsSelect<false> | AdminsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'menu-items': MenuItemsSelect<false> | MenuItemsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
    'payload-query-presets': PayloadQueryPresetsSelect<false> | PayloadQueryPresetsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    settings: Setting;
    config: Config1;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    config: ConfigSelect<false> | ConfigSelect<true>;
  };
  locale: null;
  user: Admin & {
    collection: 'admins';
  };
  jobs: {
    tasks: {
      createCollectionExport: TaskCreateCollectionExport;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: number;
  name: string;
  preferences?: {
    /**
     * Receive email notifications from the system.
     */
    emails?: boolean | null;
    /**
     * Show the admin bar on the site.
     */
    adminBar?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  private?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    landscape?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  blocks?:
    | (
        | ContactBlock
        | CtaBannerBlock
        | ContentBlock
        | GalleryBlock
        | HoursBlock
        | IntroStripBlock
        | MenuBlock
        | MediaTextBlock
        | PageHeroBlock
        | TeamBlock
        | TestimonialsBlock
        | TextHeroBlock
      )[]
    | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  slug: string;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock".
 */
export interface ContactBlock {
  label?: string | null;
  title?: string | null;
  richText?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  details?:
    | {
        /**
         * e.g. Address, Phone, Email, Hours
         */
        label: string;
        /**
         * CG icon: coffee | breakfast | cake | sandwich | dine | star | vegetarian | phone | location | clock | funfact. Or use an emoji.
         */
        icon?: string | null;
        value: string;
        id?: string | null;
      }[]
    | null;
  settings: {
    py: 'none' | 'small' | 'medium' | 'large';
    /**
     * The anchor for the block. Used for in-page links.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'contact';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBannerBlock".
 */
export interface CtaBannerBlock {
  /**
   * Small label above the title, e.g. 'Join the Team'
   */
  label?: string | null;
  title: string;
  description?: string | null;
  button: {
    linkType: 'internal' | 'custom';
    newTab?: boolean | null;
    internalLink?:
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'media';
          value: number | Media;
        } | null);
    customLink?: string | null;
    label: string;
    id?: string | null;
  };
  settings: {
    py: 'none' | 'small' | 'medium' | 'large';
    /**
     * The anchor for the block. Used for in-page links.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  image?: (number | null) | Media;
  /**
   * A short summary of the article.
   */
  summary?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  slug: string;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  settings: {
    width: 'container' | 'full' | 'wide' | 'narrow';
    backgroundColor: 'none' | 'white' | 'light' | 'primary' | 'secondary' | 'charcoal2' | 'charcoal3';
    py: 'none' | 'small' | 'medium' | 'large';
    /**
     * The anchor for the container. This will be used to link to the container.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  label?: string | null;
  title: string;
  images: {
    image: number | Media;
    id?: string | null;
  }[];
  settings: {
    py: 'none' | 'small' | 'medium' | 'large';
    /**
     * The anchor for the block. Used for in-page links.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HoursBlock".
 */
export interface HoursBlock {
  hoursLabel?: string | null;
  hoursTitle?: string | null;
  hours: {
    /**
     * e.g. Monday – Friday, Saturday
     */
    day: string;
    /**
     * e.g. 7:30am – 4:00pm
     */
    time: string;
    id?: string | null;
  }[];
  findUsLabel?: string | null;
  findUsTitle?: string | null;
  /**
   * Full address (newlines for formatting)
   */
  address: string;
  phone?: string | null;
  settings: {
    py: 'none' | 'small' | 'medium' | 'large';
    /**
     * The anchor for the block. Used for in-page links.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'hours';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroStripBlock".
 */
export interface IntroStripBlock {
  items: {
    /**
     * CG icon: coffee | breakfast | cake | sandwich | dine | star | vegetarian | phone | location | clock | funfact
     */
    icon: string;
    label: string;
    description: string;
    id?: string | null;
  }[];
  settings: {
    py: 'none' | 'small' | 'medium' | 'large';
    /**
     * The anchor for the block. Used for in-page links.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'introStrip';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MenuBlock".
 */
export interface MenuBlock {
  heading: {
    label?: string | null;
    title: string;
    description?: string | null;
  };
  settings: {
    py: 'none' | 'small' | 'medium' | 'large';
    /**
     * The anchor for the block. Used for in-page links.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'menu';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaTextBlock".
 */
export interface MediaTextBlock {
  media: number | Media;
  /**
   * e.g. Our Story
   */
  label?: string | null;
  /**
   * Last word will be styled in gold
   */
  title?: string | null;
  richText?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional button below the body
   */
  link: {
    linkType: 'internal' | 'custom';
    newTab?: boolean | null;
    internalLink?:
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'media';
          value: number | Media;
        } | null);
    customLink?: string | null;
    label: string;
    id?: string | null;
  };
  /**
   * e.g. 100% Fresh daily, Local Sourcing
   */
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  settings: {
    py: 'none' | 'small' | 'medium' | 'large';
    /**
     * The anchor for the block. Used for in-page links.
     */
    anchor?: string | null;
    /**
     * Reverse the stacking order on desktop
     */
    reverse?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageHeroBlock".
 */
export interface PageHeroBlock {
  /**
   * Small labels above the title
   */
  eyebrow?: {
    label?: string | null;
    label2?: string | null;
  };
  title: string;
  subtitle?: string | null;
  media: number | Media;
  links?:
    | {
        linkType: 'internal' | 'custom';
        newTab?: boolean | null;
        internalLink?:
          | ({
              relationTo: 'posts';
              value: number | Post;
            } | null)
          | ({
              relationTo: 'pages';
              value: number | Page;
            } | null)
          | ({
              relationTo: 'media';
              value: number | Media;
            } | null);
        customLink?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  settings: {
    width: 'container' | 'full' | 'wide' | 'narrow';
    backgroundColor: 'none' | 'white' | 'light' | 'primary' | 'secondary' | 'charcoal2' | 'charcoal3';
    py: 'none' | 'small' | 'medium' | 'large';
    /**
     * The anchor for the container. This will be used to link to the container.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'pageHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamBlock".
 */
export interface TeamBlock {
  settings: {
    py: 'none' | 'small' | 'medium' | 'large';
    /**
     * The anchor for the block. Used for in-page links.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'team';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  label?: string | null;
  title: string;
  items: {
    stars: number;
    quote: string;
    /**
     * Single letter for avatar, e.g. S
     */
    authorInitial: string;
    authorName: string;
    /**
     * e.g. Regular visitor, Via Google Reviews
     */
    authorSub?: string | null;
    id?: string | null;
  }[];
  settings: {
    py: 'none' | 'small' | 'medium' | 'large';
    /**
     * The anchor for the block. Used for in-page links.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextHeroBlock".
 */
export interface TextHeroBlock {
  /**
   * Small label above the title, e.g. 'The People Behind the Cup'
   */
  label?: string | null;
  /**
   * The last word will be styled in italic/gold
   */
  title: string;
  subtitle?: string | null;
  settings: {
    py: 'none' | 'small' | 'medium' | 'large';
    /**
     * The anchor for the block. Used for in-page links.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'textHero';
}
/**
 * Manage menu items. Used by the Menu block on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-items".
 */
export interface MenuItem {
  id: number;
  name: string;
  /**
   * e.g. Breakfast, Lunch, Drinks
   */
  category: 'breakfast' | 'lunch' | 'cakes-bakes' | 'drinks' | 'dinner';
  /**
   * e.g. £9.50, from £3.00
   */
  price: string;
  description?: string | null;
  /**
   * e.g. Most Popular, Vegetarian, Vegan
   */
  badge?: string | null;
  /**
   * Lower numbers appear first within the category.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Team members shown on the Team page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  /**
   * Optional. If empty, initials are shown.
   */
  photo?: (number | null) | Media;
  /**
   * Determines card layout: owners (2-col), manager, supervisor, crew grid.
   */
  role: 'owner' | 'manager' | 'supervisor' | 'crew';
  /**
   * e.g. "Co-Owner & Head of Operations"
   */
  jobTitle: string;
  bio: string;
  /**
   * e.g. "Double espresso, no sugar"
   */
  favouriteOrder?: string | null;
  /**
   * e.g. "Trained as a chef before switching to front of house"
   */
  funFact?: string | null;
  /**
   * Sort order within role. Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  name?: string | null;
  email?: string | null;
  phone?: string | null;
  message?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: number;
  name?: string | null;
  format?: ('csv' | 'json') | null;
  limit?: number | null;
  sort?: string | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'createCollectionExport';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'createCollectionExport') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'admins';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'menu-items';
        value: number | MenuItem;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'exports';
        value: number | Export;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'payload-jobs';
        value: number | PayloadJob;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-query-presets".
 */
export interface PayloadQueryPreset {
  id: number;
  title: string;
  isShared?: boolean | null;
  access?: {
    read?: {
      constraint?: ('everyone' | 'onlyMe' | 'specificUsers') | null;
      users?: (number | Admin)[] | null;
    };
    update?: {
      constraint?: ('everyone' | 'onlyMe' | 'specificUsers') | null;
      users?: (number | Admin)[] | null;
    };
    delete?: {
      constraint?: ('everyone' | 'onlyMe' | 'specificUsers') | null;
      users?: (number | Admin)[] | null;
    };
  };
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  columns?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  relatedCollection: 'media' | 'pages' | 'posts' | 'form-submissions';
  /**
   * This is a tempoary field used to determine if updating the preset would remove the user's access to it. When `true`, this record will be deleted after running the preset's `validate` function.
   */
  isTemp?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  name?: T;
  preferences?:
    | T
    | {
        emails?: T;
        adminBar?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  private?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        landscape?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  blocks?:
    | T
    | {
        contact?: T | ContactBlockSelect<T>;
        ctaBanner?: T | CtaBannerBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        hours?: T | HoursBlockSelect<T>;
        introStrip?: T | IntroStripBlockSelect<T>;
        menu?: T | MenuBlockSelect<T>;
        mediaText?: T | MediaTextBlockSelect<T>;
        pageHero?: T | PageHeroBlockSelect<T>;
        team?: T | TeamBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        textHero?: T | TextHeroBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  slug?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock_select".
 */
export interface ContactBlockSelect<T extends boolean = true> {
  label?: T;
  title?: T;
  richText?: T;
  details?:
    | T
    | {
        label?: T;
        icon?: T;
        value?: T;
        id?: T;
      };
  settings?:
    | T
    | {
        py?: T;
        anchor?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBannerBlock_select".
 */
export interface CtaBannerBlockSelect<T extends boolean = true> {
  label?: T;
  title?: T;
  description?: T;
  button?:
    | T
    | {
        linkType?: T;
        newTab?: T;
        internalLink?: T;
        customLink?: T;
        label?: T;
        id?: T;
      };
  settings?:
    | T
    | {
        py?: T;
        anchor?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  richText?: T;
  settings?:
    | T
    | {
        width?: T;
        backgroundColor?: T;
        py?: T;
        anchor?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock_select".
 */
export interface GalleryBlockSelect<T extends boolean = true> {
  label?: T;
  title?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  settings?:
    | T
    | {
        py?: T;
        anchor?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HoursBlock_select".
 */
export interface HoursBlockSelect<T extends boolean = true> {
  hoursLabel?: T;
  hoursTitle?: T;
  hours?:
    | T
    | {
        day?: T;
        time?: T;
        id?: T;
      };
  findUsLabel?: T;
  findUsTitle?: T;
  address?: T;
  phone?: T;
  settings?:
    | T
    | {
        py?: T;
        anchor?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroStripBlock_select".
 */
export interface IntroStripBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        icon?: T;
        label?: T;
        description?: T;
        id?: T;
      };
  settings?:
    | T
    | {
        py?: T;
        anchor?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MenuBlock_select".
 */
export interface MenuBlockSelect<T extends boolean = true> {
  heading?:
    | T
    | {
        label?: T;
        title?: T;
        description?: T;
      };
  settings?:
    | T
    | {
        py?: T;
        anchor?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaTextBlock_select".
 */
export interface MediaTextBlockSelect<T extends boolean = true> {
  media?: T;
  label?: T;
  title?: T;
  richText?: T;
  link?:
    | T
    | {
        linkType?: T;
        newTab?: T;
        internalLink?: T;
        customLink?: T;
        label?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  settings?:
    | T
    | {
        py?: T;
        anchor?: T;
        reverse?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageHeroBlock_select".
 */
export interface PageHeroBlockSelect<T extends boolean = true> {
  eyebrow?:
    | T
    | {
        label?: T;
        label2?: T;
      };
  title?: T;
  subtitle?: T;
  media?: T;
  links?:
    | T
    | {
        linkType?: T;
        newTab?: T;
        internalLink?: T;
        customLink?: T;
        label?: T;
        id?: T;
      };
  settings?:
    | T
    | {
        width?: T;
        backgroundColor?: T;
        py?: T;
        anchor?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamBlock_select".
 */
export interface TeamBlockSelect<T extends boolean = true> {
  settings?:
    | T
    | {
        py?: T;
        anchor?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  label?: T;
  title?: T;
  items?:
    | T
    | {
        stars?: T;
        quote?: T;
        authorInitial?: T;
        authorName?: T;
        authorSub?: T;
        id?: T;
      };
  settings?:
    | T
    | {
        py?: T;
        anchor?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextHeroBlock_select".
 */
export interface TextHeroBlockSelect<T extends boolean = true> {
  label?: T;
  title?: T;
  subtitle?: T;
  settings?:
    | T
    | {
        py?: T;
        anchor?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  summary?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  slug?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-items_select".
 */
export interface MenuItemsSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  price?: T;
  description?: T;
  badge?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  photo?: T;
  role?: T;
  jobTitle?: T;
  bio?: T;
  favouriteOrder?: T;
  funFact?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  sort?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-query-presets_select".
 */
export interface PayloadQueryPresetsSelect<T extends boolean = true> {
  title?: T;
  isShared?: T;
  access?:
    | T
    | {
        read?:
          | T
          | {
              constraint?: T;
              users?: T;
            };
        update?:
          | T
          | {
              constraint?: T;
              users?: T;
            };
        delete?:
          | T
          | {
              constraint?: T;
              users?: T;
            };
      };
  where?: T;
  columns?: T;
  relatedCollection?: T;
  isTemp?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  general: {
    logo: number | Media;
    /**
     * Displayed in browser tabs and bookmarks. Should be square and at least 512x512 pixels. Must be a PNG file.
     */
    favicon?: (number | null) | Media;
  };
  seo: {
    /**
     * Site title
     */
    title: string;
    /**
     * Separator between title and site name
     */
    titleSeparator?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  integrations?: {
    /**
     * Google Tag Manager ID
     */
    googleTagManager?: string | null;
    /**
     * Google Analytics tracking ID
     */
    googleAnalytics?: string | null;
    custom?: {
      /**
       * Custom code added in the <head> tag.
       */
      head?: string | null;
      /**
       * Custom code added after the opening <body> tag.
       */
      bodyOpen?: string | null;
      /**
       * Custom code added before the closing </body> tag.
       */
      bodyClose?: string | null;
    };
  };
  socials?: {
    /**
     * Link to your LinkedIn profile
     */
    linkedin?: string | null;
  };
  header: {
    /**
     * Optional button (e.g. Book a Table) shown in the nav
     */
    ctaLink: {
      linkType: 'internal' | 'custom';
      newTab?: boolean | null;
      internalLink?:
        | ({
            relationTo: 'posts';
            value: number | Post;
          } | null)
        | ({
            relationTo: 'pages';
            value: number | Page;
          } | null)
        | ({
            relationTo: 'media';
            value: number | Media;
          } | null);
      customLink?: string | null;
      label: string;
      id?: string | null;
    };
    menu?: (LinkBlock | SubMenuBlock)[] | null;
  };
  footer?: {
    /**
     * e.g. Est. 2025 · England
     */
    established?: string | null;
    /**
     * Short description below the logo
     */
    tagline?: string | null;
    facebook?: string | null;
    instagram?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinkBlock".
 */
export interface LinkBlock {
  linkType: 'internal' | 'custom';
  newTab?: boolean | null;
  internalLink?:
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  customLink?: string | null;
  label: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'link';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SubMenuBlock".
 */
export interface SubMenuBlock {
  label: string;
  links?:
    | {
        linkType: 'internal' | 'custom';
        newTab?: boolean | null;
        internalLink?:
          | ({
              relationTo: 'posts';
              value: number | Post;
            } | null)
          | ({
              relationTo: 'pages';
              value: number | Page;
            } | null)
          | ({
              relationTo: 'media';
              value: number | Media;
            } | null);
        customLink?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'subMenu';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "config".
 */
export interface Config1 {
  id: number;
  site: {
    logo: number | Media;
    logoDark: number | Media;
    /**
     * The email address displayed on the site.
     */
    email: string;
    /**
     * The telephone number displayed on the site.
     */
    phone: string;
    linkedin?: string | null;
    github?: string | null;
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  footer?: {
    summary?: string | null;
    services?:
      | {
          linkType: 'internal' | 'custom';
          newTab?: boolean | null;
          internalLink?:
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'media';
                value: number | Media;
              } | null);
          customLink?: string | null;
          label: string;
          id?: string | null;
        }[]
      | null;
    solutions?:
      | {
          linkType: 'internal' | 'custom';
          newTab?: boolean | null;
          internalLink?:
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'media';
                value: number | Media;
              } | null);
          customLink?: string | null;
          label: string;
          id?: string | null;
        }[]
      | null;
    about?:
      | {
          linkType: 'internal' | 'custom';
          newTab?: boolean | null;
          internalLink?:
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'media';
                value: number | Media;
              } | null);
          customLink?: string | null;
          label: string;
          id?: string | null;
        }[]
      | null;
    footerText?: string | null;
  };
  email: {
    /**
     * Email address(es) to receive contact form submissions. Use commas to add multiple.
     */
    emailTo: string;
    subject: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  general?:
    | T
    | {
        logo?: T;
        favicon?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        titleSeparator?: T;
        description?: T;
        image?: T;
      };
  integrations?:
    | T
    | {
        googleTagManager?: T;
        googleAnalytics?: T;
        custom?:
          | T
          | {
              head?: T;
              bodyOpen?: T;
              bodyClose?: T;
            };
      };
  socials?:
    | T
    | {
        linkedin?: T;
      };
  header?:
    | T
    | {
        ctaLink?:
          | T
          | {
              linkType?: T;
              newTab?: T;
              internalLink?: T;
              customLink?: T;
              label?: T;
              id?: T;
            };
        menu?:
          | T
          | {
              link?: T | LinkBlockSelect<T>;
              subMenu?: T | SubMenuBlockSelect<T>;
            };
      };
  footer?:
    | T
    | {
        established?: T;
        tagline?: T;
        facebook?: T;
        instagram?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinkBlock_select".
 */
export interface LinkBlockSelect<T extends boolean = true> {
  linkType?: T;
  newTab?: T;
  internalLink?: T;
  customLink?: T;
  label?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SubMenuBlock_select".
 */
export interface SubMenuBlockSelect<T extends boolean = true> {
  label?: T;
  links?:
    | T
    | {
        linkType?: T;
        newTab?: T;
        internalLink?: T;
        customLink?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "config_select".
 */
export interface ConfigSelect<T extends boolean = true> {
  site?:
    | T
    | {
        logo?: T;
        logoDark?: T;
        email?: T;
        phone?: T;
        linkedin?: T;
        github?: T;
        title?: T;
        image?: T;
        description?: T;
      };
  footer?:
    | T
    | {
        summary?: T;
        services?:
          | T
          | {
              linkType?: T;
              newTab?: T;
              internalLink?: T;
              customLink?: T;
              label?: T;
              id?: T;
            };
        solutions?:
          | T
          | {
              linkType?: T;
              newTab?: T;
              internalLink?: T;
              customLink?: T;
              label?: T;
              id?: T;
            };
        about?:
          | T
          | {
              linkType?: T;
              newTab?: T;
              internalLink?: T;
              customLink?: T;
              label?: T;
              id?: T;
            };
        footerText?: T;
      };
  email?:
    | T
    | {
        emailTo?: T;
        subject?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    name?: string | null;
    format?: ('csv' | 'json') | null;
    limit?: number | null;
    sort?: string | null;
    drafts?: ('yes' | 'no') | null;
    selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
    fields?: string[] | null;
    collectionSlug: string;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    user?: string | null;
    userCollection?: string | null;
    exportsCollection?: string | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ButtonBlock".
 */
export interface ButtonBlock {
  variant: 'default' | 'outline' | 'link' | 'ghost';
  linkType: 'internal' | 'custom';
  newTab?: boolean | null;
  internalLink?:
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  customLink?: string | null;
  label: string;
  align: 'left' | 'center' | 'right';
  id?: string | null;
  blockName?: string | null;
  blockType: 'button';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}